// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function makeProps(prim, prim$1) {
  return {
          message: prim
        };
}

var make = React.lazy((function (param) {
        return import("./Component1.bs.js").then((function (res) {
                      var Res = Object.values(res.default);
                      return Promise.resolve({
                                  default: Res[/* make */0]
                                });
                    }));
      }));

var LazyComponent1 = /* module */[
  /* makeProps */makeProps,
  /* make */make
];

exports.LazyComponent1 = LazyComponent1;
/* make Not a pure module */
